name: Cygwin
on: [push, pull_request]

jobs:
  cygport:
    name: cygport
    runs-on:  windows-latest
    steps:
    - name: Turn off line ending conversion in git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/cache@v1
      with:
        path: C:\cygwin-packages
        key: cygwin-packages-${{ hashFiles('**') }}
        restore-keys: cygwin-packages-
    - name: Fetch Cygwin installer
      run: |
        Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile C:\setup.exe
      shell: powershell
      # installer should be cacheable
    - name: Install Cygwin
      run: |
        c:\setup.exe -qgnO -s http://mirrors.kernel.org/sourceware/cygwin/ -l C:\cygwin-packages\ -P ^
        aspell,^
        automake,^
        automoc4,^
        bzr,^
        cmake,^
        cvs,^
        diffstat,^
        dos2unix,^
        gcc-g++,^
        git,^
        git-archive-all,^
        gnome-common,^
        help2man,^
        libcrypt-devel,^
        libGL-devel,^
        libkdecore5-devel,^
        libQtTest4-devel,^
        lndir,^
        lua-devel,^
        make,^
        mate-common,^
        mercurial,^
        meson,^
        mm-common,^
        monotone,^
        ninja,^
        patch,^
        perl,^
        perl-Module-Build,^
        python2,^
        robodoc,^
        ruby,^
        subversion,^
        unzip,^
        xfce4-dev-tools
      shell: cmd
    - name: Set PATH
      run: |
        echo '::set-env name=PATH::C:\cygwin64\bin;%SYSTEMROOT%\system32'
    - name: Build
      run: |
        chattr -R +C .
        bash -c 'meson _build && ninja -C _build'
    - name: Test
      run: |
        bash -c 'ninja -C _build test'
